CREATE TABLE Department(
    ID INT NOT NULL UNIQUE,
	CODE VARCHAR(45) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    PRIMARY KEY(ID)
);
CREATE TABLE LocationType(
	CODE CHAR(1) NOT NULL UNIQUE,
	TITLE VARCHAR(255) NOT NULL,
	PRIMARY KEY(CODE)
);
CREATE TABLE Facility(
    ID VARCHAR(10) NOT NULL UNIQUE,
    --LocName VARCHAR(255) NOT NULL,
	Address VARCHAR(255) NOT NULL,
	LocType CHAR(1) NOT NULL,
	PRIMARY KEY(DEPT_ID),
	FOREIGN KEY(LOCATION_TYPE) REFERENCES LocationType(CODE)
);
CREATE TABLE Clearance(
	ID INT NOT NULL UNIQUE,
	LevelDesc VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE JobCategory (
	ID INT NOT NULL UNIQUE,
	DESCRIPT VARCHAR(255) NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE Job(
	ID INT NOT NULL UNIQUE,
	Title VARCHAR(255),
	Category INT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(TYPE_ID) REFERENCES JOB_T(ID)
);
CREATE TABLE PersonnelClass(
	ID VARCHAR(2) NOT NULL,
	ClassDesc VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);
CREATE TABLE Personnel(
	ID VARCHAR(12) NOT NULL UNIQUE,
	FirstName VARCHAR(255) NOT NULL,
	MiddleName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	
	PersClass VARCHAR(1) NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(PersClass) REFERENCES PersonnelClass(ID)
);