INSERT INTO Department(ID,CODE,TITLE) VALUES
(0,"ALC","Alchemy Department"),
(1,"AEED","Anomalous Enitity Engagement Division"),
(2,"ANTD","Antimemetics Division"),
(3,"AIAD","Artificial Intelligence Applications Division"),
(4,"CRD","Cryptozoology Division"),
(5,"DCOM","Decommissioning Department"),
(6,"DEL","Department of Deletions"),
(7,"ENT","Department of Entomology"),
(8,"ETTRA","Emergent Threat Tactical Response Authority"),
(9,"DOFS","Fire Suppression Department"),
(10,"DOMF","Department of Mythology and Folkloristics"),
(11,"DOMC","Department of Miscommunications"),
(12,"DOP","Pataphysics Department"),
(13,"DOO","Department of Other"),
(14,"DOPL","Department of Procurement and Liquidation"),
(15,"DOS","Department of Surrealistics"),
(16,"DOTT","Department of Tactical Theology"),
(17,"TMO","Telecommunications Monitoring Office"),
(18,"DOTA","Temporal Anomalies Department"),
(19,"DOUN","Department of Unreality"),
(20,"DOAB","Department of Adnormalities");
INSERT INTO Location(